// <auto-generated />
namespace Cars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NoChange1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoChange1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506041526076_NoChange1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
